cafe/urls.py
from django.conf.urls import include,url
from .views import Home,Menu,About,Contact


urlpatterns = [
	url(r'^contact$',Contact.as_view(),name='contact'),
	url(r'^about$',About.as_view(),name='about'),
	url(r'^menu$',Menu.as_view(),name='menu'),
    url(r'^$',Home.as_view(),name='home')
]

project/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include("cafe.urls",namespace='start'))
]

cafe/models.py
from django.db import models

# Create your models here.

cafe/views.py
from django.shortcuts import render
from django.views.generic import View
# Create your views here.


class Home(View):
	template_name = "cafe/home.html"

	def get(self,request):
		return render(request,self.template_name)

class Menu(View):
	template_name = "cafe/menu.html"

	def get(self,request):
		return render(request,self.template_name)

class About(View):
	template_name = "cafe/about.html"

	def get(self,request):
		return render(request,self.template_name)

class Contact(View):
	template_name = "cafe/contact.html"

	def get(self,request):
		return render(request,self.template_name)

cafe/templates/cafe/about.html
{%extends 'base.html'%}
{%block content%}
<div class="row">
	<div class="col s12 m9">
	  <div class="card ">
	    <div class="card-image">
	      <img src="static/meatball.jpg">
	    </div>
	    <div class="card-content">
	      <h5>Where it all started</h5>
	      <p>My Mother and Father immigrated to this great nation in 1907 and brought there traditional Italian recipies with them. My wife an I carry on the tradition of great food and incredible atmosphere that my parents showed me here at Cafe Buono. Cafe Buono is an Italian American Restaurant located at 562 Farmington Avenue Bristol, CT 06010
		  We specialize in Fine Italian American Cuisine including Neapolitan Style Pizza. Voted Best Italian Food in Bristol for the past 6 years by Readers of the Bristol Press and Bristol Observer</p>
	    </div>
	  </div>
	</div>
</div>
{%endblock%}

cafe/templates/cafe/contact.html
{%extends 'base.html'%}
{%block content%}

<div class="jumbotron">
  <h1>Contact</h1>
  <p>Cafe Buono & Buono Pizza</p>
  <p>562 Farmington Avenue</p>
  <p>Bristol, CT 06010</p>
  <p>Cafe Buono 860 582 2233</p>
  <p>Buono Pizza 860 582 2234</p>
  <h4>We can not wait to accomedate you!</h4>
</div>

{%endblock%}

cafe/templates/cafe/home.html
{%extends 'base.html'%}
{%block content%}
<span class="rotate"></span>
{%endblock%}

cafe/templates/cafe/menu.html
{%extends 'base.html'%}
{%block content%}
<ul class="collection with-header menu-list">
      <li class="collection-header"><h4>Appetizers</h4></li>
      <li class="collection-item">FRIED CALAMARI 10</li>
      <li class="collection-item">FRIED ZUCCHINI WITH MARINARA SAUCE 8</li>
      <li class="collection-item">MUSSELS MARINARA 8</li>
      <li class="collection-item">CAPRESE SALAD FRESH MOZZARELLA, TOMATO, BASIL 8</li>
      <li class="collection-item">MUSSELS MARINARA 8</li>
      <li class="collection-item">MOZZARELLA IN CARROZZA FRIED MOZZARELLA SANDWICH 9</li>
      <li class="collection-item">EGGPLANT ROLLATINI 8</li>
      <li class="collection-item">ANTIPASTO PLATE OF MEATS AND CHEESES 12</li>
      <li class="collection-header"><h4>SOUPS & SALADS</h4></li>
      <li class="collection-item">SOUP OF THE DAY 5</li>
      <li class="collection-item">A HEARTY PASTA AND BEAN SOUP WITH FRESH VEGETABLES IN A TOMATO BASE 6</li>
      <li class="collection-item">ESCAROLE & BEAN 6</li>
      <li class="collection-item">SPINACH SALAD 8</li>
      <li class="collection-item">CAESAR SALAD 8</li>
      <li class="collection-item">MESCLUN SALAD 9</li>
      <li class="collection-header"><h4>SIDES</h4></li>
      <li class="collection-item">MEATBALLS 5</li>
      <li class="collection-item">SAUSAGE 6</li>
      <li class="collection-item">SAUTEED SPINACH, GARLIC &amp; OLIVE OIL 4</li>
      <li class="collection-item">FRENCH FRIES 4</li>
      <li class="collection-item">SAUTEED MUSHROOMS &amp; ONIONS 5</li>
      <li class="collection-header"><h4>PASTA</h4></li>
      <li class="collection-item">FETTUCINI BOLOGNESE 15</li>
      <li class="collection-item">PENNE ALIA VODKA 12</li>
      <li class="collection-item">RIGATONI AMANTRICIANA 15</li>
      <li class="collection-item">SPAGHETTI ALA CARBONARA 14</li>
      <li class="collection-item">FETTUCINI ALFREDO 13</li>
      <li class="collection-item">PENNE ARRABBIATA 12</li>
      <li class="collection-item">POMODORO 12</li>
      <li class="collection-item">MACARONI & CHEESE 15</li>
      <li class="collection-item">SPAGHETTI &amp; MEATBALLS 13</li>
      <li class="collection-item">BAKED MANICOTTI 14</li>
      <li class="collection-item">BAKED MEAT LASAGNA 16</li>
      <li class="collection-item">PASTA PRIMAVERA 15</li>
      <li class="collection-header"><h4>PARMIGIANA</h4></li>
      <li class="collection-item">LIGHTLY BREADED AND SERVED GOLDEN BROWN WITH MARINARA SAUCE AND MOZZERALLA CHEESE, SERVED OVER PENNE PASTA <p>EGGPLANT 14 CHICKEN 15 VEAL 19</p></li>
      <li class="collection-header"><h4>MARSALA</h4></li>
      <li class="collection-item">CLASSIC DISH MADE WITH MARSALA WINE, SLICED MUSHROOMS AND A LIGHT BROWN SAUCE<p>CHICKEN 15 VEAL 19</p></li>
      <li class="collection-header"><h4>PICATTA</h4></li>
      <li class="collection-item">A LIGHT LEMON BUTTER &amp; WINE SAUCE WITH CAPERS <p>CHICKEN 15 VEAL 19 SHRIMP 18</p></li>
      <li class="collection-header"><h4>FRANCESE</h4></li>
      <li class="collection-item">LIGHTLY BATTERED AND SAUTEED WITH LEMON BUTTER &amp; WHITE WINE <p>CHICKEN 15 VEAL 19</p></li>
      <li class="collection-header"><h4>CHICKEN AGRODOLCE</h4></li>
      <li class="collection-item">SWEET &amp; SOUR SICILIAN CHICKEN 16</li>
      <li class="collection-header"><h4>CHICKEN SORENTINO</h4></li>
      <li class="collection-item">CHICKEN LAYERED WITH PROSCIUTTO, EGGPLANT, SPINACH AND CREAM CHEESE FINISHED IN A LIGHT BROWN SAUCE 18</li>
      <li class="collection-header"><h4>CHICKEN ROLLATINI</h4></li>
      <li class="collection-item">A PROSCIUTTO &amp; RICOTTA CHEESE MIX STUFFED CHICKEN BREAST SAUTEED IN A MUSHROOM MARSALA SAUCE 17</li>
      <li class="collection-header"><h4>CHICKEN SAN REMO</h4></li>
      <li class="collection-item">CHICKEN SAUTEED WITH OVEN ROASTED TOMATOES, PEAS, MUSHROOMS IN A WHITE WINE GARLIC SAUCE 18</li>
      <li class="collection-header"><h4>VEAL SALTIMBOCCA</h4></li>
      <li class="collection-item">TENDER VEAL CUTLET WITH PROSCIUTTO AND SAGE IN A LIGHT MARSALA BUTTER SAUCE 20</li>
      <li class="collection-header"><h4>VEAL CASA BLANCA</h4></li>
      <li class="collection-item">AN OLD BUONO FAVORITE! PILLOWS OF VEAL STUFFED WITH A RICOTTA CHEESE MIXTURE, DRESSED WITH OUR HOUSE VODKA SAUCE 20</li>
      <li class="collection-header"><h4>VEAL ROLLATINI</h4></li>
      <li class="collection-item">A PROSCIUTTO &amp; RICOTTA CHEESE MIX, SPINACH STUFFED VEAL CUTLET, SAUTEED IN A MUSHROOM MARSALA SAUCE 20</li>
      <li class="collection-header"><h4>FILET MIGNON BAROLO</h4></li>
      <li class="collection-item">8 OZ CENTER CUT FILET WITH GOAT CHEESE, FRESH HERBS AND A BAROLO WINE REDUCTION 24</li>
      <li class="collection-header"><h4>NY STRIP GORGONZOLA</h4></li>
      <li class="collection-item">12 0Z CENER CUT STRIP WITH CARMELIZED ONIONS, MUSHROOMS AND GORGONZOLA CHEESE SAUCE 20</li>
      <li class="collection-header"><h4>FILET TIPS</h4></li>
      <li class="collection-item">TIPS SAUTEED WITH MUSHROOMS, PEPPERS, ONIONS IN A BROWN SAUCE OVER FETTUCINE 20</li>
      <li class="collection-header"><h4>SHRIMP SCAMPI</h4></li>
      <li class="collection-item">SHRIMP SAUTEED IN A GARLIC FRESH HERBS AND WHITE WINE, BUTTER &amp; LEMON SAUCE OVER LINGUINI 20</li>
      <li class="collection-header"><h4>SEAFOOD FRADIABLO</h4></li>
      <li class="collection-item">SHRIMP, COD, CLAMS, MUSSELS, CALAMARI IN A SPICY MARINARA SAUCE SERVED OVER LINGUINI 21</li>
      <li class="collection-header"><h4>SALMON GRIGLIATO</h4></li>
      <li class="collection-item">CHAR-GRILLED SALMON WITH LEMON AND CAPER SAUCE 18</li>
      <li class="collection-header"><h4>STUFFED SOLE FLORENTINE</h4></li>
      <li class="collection-item">SOLE STUFFED WITH SPINACH IN A WHITE WINE BUTTER SAUCE 19</li>
      <li class="collection-header"><h4>BAKED COD</h4></li>
      <li class="collection-item">COD BAKED WITH SPINACH AND ARTICHOKES FINISHED IN A WHITE WINE LEMON SAUCE 18</li>
      <li class="collection-header"><h4>CLAMS &amp; LINGUINI</h4></li>
      <li class="collection-item">WHOLE CLAMS IN A RED OR WHITE WINE SAUCE 18</li>
      <li class="collection-header"><h4>KIDS MENU</h4></li>
      <li class="collection-item">PASTA AL BUNO SPAGHETTI WITH BUTTER 5</li>
      <li class="collection-item">CHICKEN PARMIGIANA WITH LINGUINI 8</li>
      <li class="collection-item">SPAGHETTI &amp; MEATBALL 7</li>
      <li class="collection-item">CHEESE RAVIOLI WITH MARINARA 7</li>
      <li class="collection-header"><h4>COFFEE</h4></li>
      <li class="collection-item">EXPRESSO 2.50</li>
      <li class="collection-item">AMERICANO 2.50</li>
      <li class="collection-item">CAPPUCINO 4.00</li>
      <li class="collection-item">AMERICAN COFFEE 2.00</li>
      <li class="collection-item">TEA 2.00</li>
    </ul>
{%endblock%}

templates/base.html
<!DOCTYPE>
{%load staticfiles%}
<html>
<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
	<script src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
	<!--<script type="text/javascript" src="jquery.text-rotator.js"></script>
	<link rel="stylesheet" type="text/css" href="jquery.text-rotator.css" />-->
	<title>Cafe Buono</title>
</head>
<body>
	<div class="navbar-fixed">
		<nav>
			<div class="nav-wrapper menu">
			  	<ul>
			  		<div class="row">
			  			<li class="link-list"><a href="{%url 'start:home'%}"><img class="logo" src="../static/logo.jpg"></a></li>
			        </div>
			        <div class="row">
			        	<li class="link-list"><a href="{%url 'start:menu'%}"><h4>Menu</h4></a></li>
			        </div>
			        <div class="row">
			        	<li class="link-list"><a href="{%url 'start:about'%}"><h4>About Us</h4></a></li>
			        </div>
			        <div class="row">
			        	<li class="link-list"><a href="http://cafebuonobristolct.com/"><h4>Order Online</h4></a></li>
			        </div>
			        <div class="row">
			        	<li class="link-list"><a href="{%url 'start:contact'%}"><h4>Contact</h4></a></li>
			        </div>
			  	</ul>
			  </div>
			</div>
		</nav>
	</div>
	<div class="container">
	{%block content%}

	{%endblock%}
	</div>
</body>
</html>